### ISSUE TITLE
Support WinGet package manager for Windows 10+

### ISSUE THREAD

**Issue by IGR2014** [ninja-build/ninja#2022]
It would be really great to have ability to just install ninja like that out of the box:

`windget install --id=NinjaBuild.NinjaBuild`

Here is some instructions how it can be done: [Microsoft Docs](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Cversion-example)

**Comment by scivision** [comment]
CMake's winget [yaml](https://github.com/microsoft/winget-pkgs/tree/master/manifests/k/Kitware/CMake/3.22.0) looks straightforward, it wants an .msi installer

**Comment by IGR2014** [comment]
About ".yaml for winget" seems like it should be generated with [YAMLCreate.ps1](https://github.com/microsoft/winget-pkgs/blob/master/doc/tools/YamlCreate.md) from [winget-pkgs](https://github.com/microsoft/winget-pkgs) repo..
But this does not seems to be logical - clone whole repo during CI just for one script.

I can suggest something like this if "Ninja.Ninja" would be ok for package ID. So the left-overs are how to generate InstallerSha256 (should be easy) and ProductCode (have not found info yet).

```
# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: "Ninja.Ninja"
PackageVersion: "1.10.3" # Note 1.10.3 beacuse 1.10.2 already exist without .msi
InstallerLocale: "en-US"
PublisherUrl: "https://github.com/ninja-build/ninja"
PublisherSupportUrl: "https://github.com/ninja-build/ninja/issues/new"
License: "Apache License 2.0"
LicenseUrl: "https://github.com/ninja-build/ninja/blob/master/COPYING"
ShortDescription: "Ninja is a small build system with a focus on speed."
MinimumOSVersion: "10.0.0.0"
InstallerType: "msi"
Scope: "machine"
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: "install"
Installers:
- Architecture: "x86"
  InstallerUrl: "https://github.com/ninja-build/ninja/releases/download/v1.10.3/ninja-windows.msi"
  InstallerSha256: # Generated with YAMLCreate.ps1
  ProductCode: # Generated with YAMLCreate.ps1
  InstallerSwitches:
    Custom: "ADD_CMAKE_TO_PATH=System"
- Architecture: "x64"
  InstallerUrl: "https://github.com/ninja-build/ninja/releases/download/v1.10.3/ninja-windows.msi"
  InstallerSha256: # Generated with YAMLCreate.ps1
  ProductCode: # Generated with YAMLCreate.ps1
  InstallerSwitches:
    Custom: "ADD_CMAKE_TO_PATH=System"
ManifestType: "installer"
ManifestVersion: "1.0.0"
```

Guess, PR with generated mainfest should be added to [winget-pkgs](https://github.com/microsoft/winget-pkgs) only after this PR acceptance.
